site_name: Xengineering Alternator Regulator Documentation
site_url: https://docs.xengineering.net
site_description: Technical documentation for Xengineering marine open-source alternator regulator system
site_author: Xengineering

repo_name: markliquid1/regulatordocumentation
repo_url: https://github.com/markliquid1/regulatordocumentation

theme:
 name: material
 features:
   - navigation.sections
   - navigation.expand
   - search.highlight

plugins:
 - search

extra_css:
 - stylesheets/extra.css

markdown_extensions:
 - admonition
 - pymdownx.highlight
 - pymdownx.superfences
 - toc:
     permalink: true

nav:
 - Home: index.md
 - Basic Use:
   - Getting Started: basic-use/getting-started.md
   - Installation: basic-use/installation.md
   - Quick Start Guide: basic-use/quick-start.md
   - Troubleshooting: basic-use/troubleshooting.md
 - Hardware:
   - System Architecture: hardware/system-architecture.md
   - Digital Inputs: hardware/digital-inputs.md
   - Digital Outputs: hardware/digital-outputs.md
   - Alternator Field Drive: hardware/field-output.md
   - Analog Inputs: hardware/analoginputsADS1115.md
   - Power Supply: hardware/power-supply.md
   - ESP32 Controller: hardware/esp32-controller.md
   - Connectors & Wiring: hardware/connectors.md
 - Software - ESP32:
   - System Overview: software/esp32/system_overview.md
   - Sensor Systems: software/esp32/sensor_systems.md
   - Communication Interfaces: software/esp32/communication_interfaces.md
   - Field Control: software/esp32/field_control_docs.md
   - Learning Mode: software/esp32/Learning_Mode_System.md
   - Battery Management: software/esp32/battery_management_docs.md
   - Network & Web System: software/esp32/network_web_system_docs.md
   - Safety & Monitoring: software/esp32/safety_monitoring_docs.md
   - Advanced Features: software/esp32/advanced_features_docs.md
   - Configuration: software/esp32/configuration_development_docs.md
 - Software - Client:
   - Web Interface Overview: software/client/web-interface-overview.md
   - HTML Structure: software/client/html.md
   - JavaScript Logic: software/client/javascript.md
   - CSS Styling: software/client/css.md
   - Real-time Data Flow: software/client/realtime-data.md
 - Local Xengineering Ref Only:
   - Partitioning: localstuff for Xengineering ref/esp32_partition_guide.md
   - MkDocs Guide: localstuff for Xengineering ref/mkdocs_setup_guide.md
   - OTA: localstuff for Xengineering ref/updated_ota_docs V3.md
   - Planning: localstuff for Xengineering ref/updated_planning_doc.md

copyright: Copyright &copy; 2025 Xengineering