site_name: Alternator Regulator Documentation
site_url: https://docs.xengineering.net
site_description: Technical docs for Xengineering marine open-source alternator regulator system
site_author: Xengineering

repo_name: markliquid1/regulatordocumentation
repo_url: https://github.com/markliquid1/regulatordocumentation

theme:
 name: material
 features:
   - navigation.sections
   - navigation.expand
   - search.highlight

plugins:
 - search

extra_css:
 - stylesheets/extra.css

markdown_extensions:
 - admonition
 - pymdownx.highlight
 - pymdownx.superfences
 - toc:
     permalink: true

nav:
 - Home: index.md
 - Intro:
   - Features: basic-use/key_features_list.md
   - Getting Started: basic-use/getting-started.md
   - Installation: basic-use/installation.md
   - Quick Start Guide: basic-use/quick-start.md
   - Troubleshooting: basic-use/troubleshooting.md
 - Hardware:
   - System Architecture: hardware/index.md
   - Digital Inputs: hardware/digital-inputs.md
   - Switching Power Supply: hardware/switching_power_supply_doc.md
   - Digital Outputs: hardware/digital-outputs.md
   - Alternator Field Drive: hardware/alternator_field_drive.md
   - Baro and Temp Sensor: hardware/bmp390_documentation.md
   - NMEA0183 and VeDirect: hardware/NMEA0183_and_VeDirect.md
   - BatteryV and Current Monitor: hardware/ina228.md
   - Warning Buzzer: hardware/buzzer_control_doc.md
   - Tachometer Output: hardware/tach_out.md
   - USB-C: hardware/usb_c.md
   - NMEA2K: hardware/nmea2k.md
   - Analog Inputs: hardware/analoginputsADS1115.md
   - Input Protection: hardware/input-protection.md
   - ESP32 Controller: hardware/esp32-brain.md
   - LM2907 Resistor Mod: hardware/lm2907 resistor mod.md
   - Connectors & Wiring: hardware/connectors.md
 - Software - ESP32:
   - System Overview: software/esp32/system_overview.md
   - Sensor Systems: software/esp32/sensor_systems.md
   - Communication Interfaces: software/esp32/communication_interfaces.md
   - Field Control: software/esp32/field_control_docs.md
   - Learning Mode: software/esp32/Learning_Mode_System.md
   - Battery Management: software/esp32/battery_management_docs.md
   - Network & Web System: software/esp32/network_web_system_docs.md
   - Safety & Monitoring: software/esp32/safety_monitoring_docs.md
   - Advanced Features: software/esp32/advanced_features_docs.md
   - Configuration: software/esp32/configuration_development_docs.md
 - Software - Client:
   - HTML Structure: software/client/html.md
   - JavaScript Logic: software/client/javascript.md
   - CSS Styling: software/client/css.md
 - Local Xengineering Ref Only:
   - Partitioning: localstuff for Xengineering ref/esp32_partition_guide.md
   - OTA: localstuff for Xengineering ref/updated_ota_docs V3 .md
   - Planning: localstuff for Xengineering ref/updated_planning_doc.md
   - Biz Stuff: localstuff for Xengineering ref/business_analysis_summary.md
   - AI Notes: localstuff for Xengineering ref/AI_notes_Aug2025.md
   - Protrak MX2e Guide: localstuff for Xengineering ref/protrak_mx2e_guide.md
   - Xregulator Backup Guide: localstuff for Xengineering ref/xregulator_backup_guide.md

copyright: Copyright &copy; 2025 Xengineering